export const Images = {
  //logo
  Logo: "/assets/logo/9xlogo3.svg",

  //banners
  banner1: "./assets/banner/banner1.svg",
  banner2: "./assets/banner/banner2.svg",
  casino1: "./assets/banner/casino1.svg",
  casino2: "./assets/banner/casino2.svg",
  cricket1: "./assets/banner/cricket1.svg",
  cricket2: "./assets/banner/cricket2.svg",
  football1: "./assets/banner/football1.svg",
  football2: "./assets/banner/football2.svg",
  tennis1: "./assets/banner/tennis1.svg",
  tennis2: "./assets/banner/tennis2.svg",

  //icons
  bellIcon1: "./assets/icons/bell1.svg",
  bank: "./assets/icons/bank.svg",
  upi: "./assets/icons/upi.svg",
  phnpay: "./assets/icons/phnpay.svg",
  paytm: "./assets/icons/paytm.svg",
  qrcode: "./assets/icons/qrcode.svg",
  gpay: "./assets/icons/gpay.svg",
  star: "./assets/icons/star1.svg",
  live: "./assets/icons/live.svg",
  thump: "./assets/icons/thump.svg",
  settings: "./assets/icons/settings.svg",
  profile1: "./assets/icons/profile1.svg",
  profile2: "./assets/icons/profile2.svg",
  pro2: "./assets/icons/pro2.svg",
  pro3: "./assets/icons/pro3.svg",
  personal: "./assets/icons/personal.svg",
  deposit: "./assets/icons/deposit.svg",
  money: "./assets/icons/money.svg",
  invite: "./assets/icons/invite.svg",
  profile2: "./assets/icons/profile2.svg",
  layer: "./assets/icons/layer.svg",
  privacy: "./assets/icons/privacy.svg",
  terms: "./assets/icons/terms.svg",
  success: "./assets/icons/success.svg",
  blocked: "./assets/icons/blocked.svg",
  bonus: "./assets/icons/bonus.svg",
  wallet: "./assets/icons/wallet.svg",

  //games
  ezugicasino: "./assets/games/ezugicasino.svg",
  img2: "./assets/games/img2.svg",
  img3: "./assets/games/img3.svg",
  img4: "./assets/games/img4.svg",
  img5: "./assets/games/img5.svg",
  img6: "./assets/games/img6.svg",
  img7: "./assets/games/img7.svg",
  img8: "./assets/games/img8.svg",
  img9: "./assets/games/img9.svg",
  img10: "./assets/games/img10.svg",
  img11: "./assets/games/img11.svg",
  img12: "./assets/games/img12.svg",
  img13: "./assets/games/img13.svg",
  img14: "./assets/games/img14.svg",
  img15: "./assets/games/img15.svg",
  img16: "./assets/games/img16.svg",
  img17: "./assets/games/img17.svg",
  img18: "./assets/games/img18.svg",
  img19: "./assets/games/img19.svg",
  img20: "./assets/games/img20.svg",
  img21: "./assets/games/img21.svg",
  img22: "./assets/games/img22.svg",
  img23: "./assets/games/img23.svg",
  img24: "./assets/games/img24.svg",
  betfair1: "./assets/games/betfair1.svg",
  sport: "./assets/games/sport.svg",
  evolution: "./assets/games/evolution.svg",
  ezugi: "./assets/games/ezugi.svg",
  royal: "./assets/games/royal.svg",
  asiagaming: "./assets/games/asiagaming.svg",
  mask: "./assets/games/mask.svg",
  facebook: "./assets/games/facebook.svg",
  bat: "./assets/games/bat.svg",
  ball: "./assets/games/ball.svg",
  tennis: "./assets/games/tennis.svg",
  grey: "./assets/games/grey.svg",
  baseball: "./assets/games/baseball.svg",
  horse: "./assets/games/horse.svg",
  bets: "./assets/games/bets.svg",
  Wallet: "./assets/games/Wallet.svg",
  pl: "./assets/games/pl.svg",
  report: "./assets/games/report.svg",
  set: "./assets/games/set.svg",
  account: "./assets/games/account.svg",
  tickets: "./assets/games/tickets.svg",
  basketball: "./assets/games/basketball.svg",
  /*PageNotFound*/
  pageNotFound: "../assets/404/page-not-found.svg",
  page404: "../assets/404/404.svg",

  // Mobile Menu Icons
  homeIcon: "/assets/icons/mobile-menu-list/home.svg",
  liveIcon: "/assets/icons/mobile-menu-list/live.svg",
  casinoIcon: "/assets/icons/mobile-menu-list/poker-chip.svg",
  sportsIcon: "/assets/icons/mobile-menu-list/sports.svg",
  myBets: "/assets/icons/mobile-menu-list/my-bets.svg",
  myWallet: "/assets/icons/mobile-menu-list/my-wallet.svg",
  accountStatement: "/assets/icons/mobile-menu-list/account-statement.svg",
  plStatement: "/assets/icons/mobile-menu-list/p_l.svg",
  commissionReport: "/assets/icons/mobile-menu-list/commision_report.svg",
  setButtonVariables: "/assets/icons/mobile-menu-list/set_buttons.svg",
  logoutIcon: "/assets/icons/mobile-menu-list/log_out.svg",
};
